name: flutter_gcaptcha_v3
description: Implementation of Google reCAPTCHA v3 for Flutter (IOS/Android)
version: 0.0.6
repository: https://github.com/basnetjiten/flutter_gcaptcha_v3

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter


  #webview
  webview_flutter_plus: ^0.3.0+2

  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  #functional programmings
  dartz: ^0.10.1


flutter:
  uses-material-design: true
  assets:
    - packages/flutter_gcaptcha_v3/assets/index.html

